CREATE DATABASE CODESOLUTIONS DEFAULT CHARACTER SET utf8;


USE CODESOLUTIONS;


SELECT DATABASE();


CREATE TABLE CLIENTE (
    IDCLI INT auto_increment not null,
    DNICLI CHAR(8),
    NOMBRES VARCHAR(60),
    APELLIDOS VARCHAR(100),
    DIRECCION VARCHAR(50),
    CELULAR CHAR(9),
    SEXO CHAR(1),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (IDCLI)
);

INSERT INTO CLIENTE 
(DNICLI, NOMBRES, APELLIDOS, DIRECCION, CELULAR, SEXO)
VALUES
('12345678', 'Brenda', 'De La O', 'San Vicente', '123456789', 'F');

SELECT * FROM CLIENTE;


